{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/vrx.json"}, "html": {"href": "#!/osrf/vrx"}, "avatar": {"href": "data/bytebucket.org/ravatar/{e278ca38-7edb-4e62-b785-46dff5617d98}ts=2274605"}}, "type": "repository", "name": "vrx", "full_name": "osrf/vrx", "uuid": "{e278ca38-7edb-4e62-b785-46dff5617d98}"}, "links": {"attachments": {"href": "data/repositories/osrf/vrx/issues/77/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/vrx/issues/77.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/vrx/issues/77/watch"}, "comments": {"href": "data/repositories/osrf/vrx/issues/77/comments_page=1.json"}, "html": {"href": "#!/osrf/vrx/issues/77/vrx-tutorials-xacro-to-urdf-conversion"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/vrx/issues/77/vote"}}, "reporter": {"display_name": "Matthew", "uuid": "{4fab3323-7162-480a-9d31-3ffa84c268c0}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B4fab3323-7162-480a-9d31-3ffa84c268c0%7D"}, "html": {"href": "https://bitbucket.org/%7B4fab3323-7162-480a-9d31-3ffa84c268c0%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/5c63d9db9854722ed6777d28/fe766f71-ac94-4753-9b6d-5bac427edda4/128"}}, "nickname": "MattBowers", "type": "user", "account_id": "5c63d9db9854722ed6777d28"}, "title": "vrx tutorials: xacro to urdf conversion needs -inorder command to work", "component": null, "votes": 0, "watches": 1, "content": {"raw": "I noticed that when on the vrx tutorials about setting up a custom .urdf file that using the command given generates an error that looks like the attached picture.  After the error message the resulting urdf file had nothing in it. When running the command with the --inorder before the file name the process runs correctly and the resulting urdf file has all the appropriate information in it. \\", "markup": "markdown", "html": "<p>I noticed that when on the vrx tutorials about setting up a custom .urdf file that using the command given generates an error that looks like the attached picture.  After the error message the resulting urdf file had nothing in it. When running the command with the --inorder before the file name the process runs correctly and the resulting urdf file has all the appropriate information in it. \\</p>", "type": "rendered"}, "assignee": null, "state": "resolved", "version": null, "edited_on": null, "created_on": "2019-03-20T06:40:49.539724+00:00", "milestone": null, "updated_on": "2019-04-11T17:50:54.089247+00:00", "type": "issue", "id": 77}