{"links": {"self": {"href": "data/repositories/osrf/vrx/issues/152/comments/56883442.json"}, "html": {"href": "#!/osrf/vrx/issues/152#comment-56883442"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/vrx/issues/152.json"}}, "type": "issue", "id": 152, "repository": {"links": {"self": {"href": "data/repositories/osrf/vrx.json"}, "html": {"href": "#!/osrf/vrx"}, "avatar": {"href": "data/bytebucket.org/ravatar/{e278ca38-7edb-4e62-b785-46dff5617d98}ts=2274605"}}, "type": "repository", "name": "vrx", "full_name": "osrf/vrx", "uuid": "{e278ca38-7edb-4e62-b785-46dff5617d98}"}, "title": "Runtime Error During World Generation"}, "content": {"raw": "I cant seem to replicate this issue anymore as well. @{5b96b66385af94340e7cabce} would be great if you could mark as resolved, thanks!", "markup": "markdown", "html": "<p>I cant seem to replicate this issue anymore as well. <span class=\"ap-mention\" data-atlassian-id=\"5b96b66385af94340e7cabce\">@Tyler Lum</span> would be great if you could mark as resolved, thanks!</p>", "type": "rendered"}, "created_on": "2020-04-10T03:28:04.441043+00:00", "user": {"display_name": "Hashir Zahir", "uuid": "{0033cdb9-ea6e-4c6a-a9ad-d462a485643d}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B0033cdb9-ea6e-4c6a-a9ad-d462a485643d%7D"}, "html": {"href": "https://bitbucket.org/%7B0033cdb9-ea6e-4c6a-a9ad-d462a485643d%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/3c71628af17207fad1dd0ea6280b41f1d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsHZ-5.png"}}, "nickname": "hzahir", "type": "user", "account_id": "557058:6b6463b7-2835-47c7-8c22-fdef36e9e325"}, "updated_on": null, "type": "issue_comment", "id": 56883442}