{"links": {"self": {"href": "data/repositories/osrf/vrx/pullrequests/16/comments/69427272.json"}, "html": {"href": "#!/osrf/vrx/pull-requests/16/_/diff#comment-69427272"}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 16, "links": {"self": {"href": "data/repositories/osrf/vrx/pullrequests/16.json"}, "html": {"href": "#!/osrf/vrx/pull-requests/16"}}, "title": "Add simple test to ensure sandisland / wamv spawns"}, "content": {"raw": "I got the following error while running the test:\n\n    Scanning dependencies of target _run_tests_robotx_gazebo_rostest_test_sandisland.test\n    -- run_tests.py: execute commands\n      /opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/developer/vmrc_ws/src/vmrc/robotx_gazebo --package=robotx_gazebo --results-filename test_sandisland.xml --results-base-dir /home/developer/vmrc_ws/build/test_results /home/developer/vmrc_ws/src/vmrc/robotx_gazebo/test/sandisland.test \n    ... logging to /home/developer/.ros/log/rostest-f0b9cad11f05-25902.log\n    [ROSUNIT] Outputting test results to /home/developer/vmrc_ws/build/test_results/robotx_gazebo/rostest-test_sandisland.xml\n    [Testcase: testsandisland_test] ... FAILURE!\n    FAILURE: Test node [robotx_gazebo/sandisland_test] does not exist or is not executable\n      File \"/usr/lib/python2.7/unittest/case.py\", line 329, in run\n        testMethod()\n      File \"/opt/ros/kinetic/lib/python2.7/dist-packages/rostest/runner.py\", line 93, in fn\n        self.fail(message)\n      File \"/usr/lib/python2.7/unittest/case.py\", line 410, in fail\n        raise self.failureException(msg)\n    --------------------------------------------------------------------------------\n    \n    [ROSTEST]-----------------------------------------------------------------------\n    \n    [testsandisland_test][failed]\n    \n    SUMMARY\n     * RESULT: FAIL\n     * TESTS: 0\n     * ERRORS: 0\n     * FAILURES: 1\n    \n    ERROR: The following tests failed to run:\n     * testsandisland_test\n\n\u200c", "markup": "markdown", "html": "<p>I got the following error while running the test:</p>\n<div class=\"codehilite\"><pre><span></span>Scanning dependencies of target _run_tests_robotx_gazebo_rostest_test_sandisland.test\n-- run_tests.py: execute commands\n  /opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/developer/vmrc_ws/src/vmrc/robotx_gazebo --package=robotx_gazebo --results-filename test_sandisland.xml --results-base-dir /home/developer/vmrc_ws/build/test_results /home/developer/vmrc_ws/src/vmrc/robotx_gazebo/test/sandisland.test \n... logging to /home/developer/.ros/log/rostest-f0b9cad11f05-25902.log\n[ROSUNIT] Outputting test results to /home/developer/vmrc_ws/build/test_results/robotx_gazebo/rostest-test_sandisland.xml\n[Testcase: testsandisland_test] ... FAILURE!\nFAILURE: Test node [robotx_gazebo/sandisland_test] does not exist or is not executable\n  File &quot;/usr/lib/python2.7/unittest/case.py&quot;, line 329, in run\n    testMethod()\n  File &quot;/opt/ros/kinetic/lib/python2.7/dist-packages/rostest/runner.py&quot;, line 93, in fn\n    self.fail(message)\n  File &quot;/usr/lib/python2.7/unittest/case.py&quot;, line 410, in fail\n    raise self.failureException(msg)\n--------------------------------------------------------------------------------\n\n[ROSTEST]-----------------------------------------------------------------------\n\n[testsandisland_test][failed]\n\nSUMMARY\n * RESULT: FAIL\n * TESTS: 0\n * ERRORS: 0\n * FAILURES: 1\n\nERROR: The following tests failed to run:\n * testsandisland_test\n</pre></div>\n\n\n<p>\u200c</p>", "type": "rendered"}, "created_on": "2018-07-10T00:27:56.429851+00:00", "user": {"display_name": "Carlos Ag\u00fcero", "uuid": "{da8a8e89-4bb0-421b-bd0e-dbbed3d4ed6a}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bda8a8e89-4bb0-421b-bd0e-dbbed3d4ed6a%7D"}, "html": {"href": "https://bitbucket.org/%7Bda8a8e89-4bb0-421b-bd0e-dbbed3d4ed6a%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/692bf15758111acaddae4da15a47f9e5d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCA-0.png"}}, "nickname": "caguero", "type": "user", "account_id": "557058:4ded1ddf-947e-4154-bbd1-3dba24f1bdbd"}, "updated_on": "2018-07-10T00:27:56.436745+00:00", "type": "pullrequest_comment", "id": 69427272}